sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis
  - pip install codecov
  - pip install -r requirements.txt


script:
  - make lint
  - make test-all

after_success:
  - codecov --token=avm4PQNy8UecTz8q631p